# -1 to remove max
MAX_NESTING_LEVEL = 3
MAX_EXPRESSION_LEVEL = 3
MAX_FUNCTION_INPUT = 5
MAX_FUNCTION_OUTPUT = 5
MAX_STORAGE_VARIABLES = 5
MAX_LOCAL_VARIABLES = 5
MAX_FUNCTIONS = 5
MAX_LIST_SIZE = 100